
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: systemadmin_development


test:
  <<: *default
  database: systemadmin_test

production:
  <<: *default
  database: systemadmin_production
  username: systemadmin
  password: <%= ENV['SYSTEMADMIN_DATABASE_PASSWORD'] %>
